#!/bin/sh

##########################################################################
#
#  Script:  hdr01_hydra12H4_qc-polish_trinity_11042025143926AEST_22042025170001AEST.pbs
#  Author:  Isabela Almeida
#  Created: Tue Apr 22 05:00:01 PM AEST 2025 at QIMR Berghofer (Brisbane, Australia) - VSC
#  Updated: Tue Apr 22 05:00:01 PM AEST 2025 at QIMR Berghofer (Brisbane, Australia) - VSC
#  Version: v01
#  Email:   Isabela.Almeida@qimrberghofer.edu.au
#
##########################################################################

#PBS -N hdr01_hydra12H4_qc-polish_trinity_11042025143926AEST_22042025170001AEST
#PBS -r n
#PBS -l mem=85GB,walltime=10:00:00,ncpus=32
#PBS -m abe
#PBS -M Isabela.Almeida@qimrberghofer.edu.au

#................................................
#  Set main working directory
#................................................

## Change to main directory
cd ${PBS_O_WORKDIR}

echo ; echo "WARNING: The main directory for this run was set to ${PBS_O_WORKDIR}"; echo 

#................................................
#  Load Softwares, Libraries and Modules
#................................................

module load transrate/1.0.3
module load fastq-pair/20231003

#................................................
#  Run step
#................................................

echo "## Run Fastq_pair at" ; date ; echo
fastq_pair -t 490622724 /working/lab_julietF/isabelaA/Project_HyDRA/benchmarking/assemblers/treated-data/trinity_11042025143926AEST/insilico_read_normalization/left.norm.fq /working/lab_julietF/isabelaA/Project_HyDRA/benchmarking/assemblers/treated-data/trinity_11042025143926AEST/insilico_read_normalization/right.norm.fq

echo "## Run TransRate at" ; date ; echo
transrate --assembly /working/lab_julietF/isabelaA/Project_HyDRA/benchmarking/assemblers/treated-data/trinity_11042025143926AEST/trinity_11042025143926AEST.Trinity.fasta --left /working/lab_julietF/isabelaA/Project_HyDRA/benchmarking/assemblers/treated-data/trinity_11042025143926AEST/insilico_read_normalization/left.norm.fq.paired.fq --right /working/lab_julietF/isabelaA/Project_HyDRA/benchmarking/assemblers/treated-data/trinity_11042025143926AEST/insilico_read_normalization/right.norm.fq.paired.fq --reference /working/lab_julietF/mainaB/ReferenceGenomes/TranscriptomeGRCh38p7_ERCC.fa --threads 32 --output hydra12H4_qc-and-polish_TransRate_22042025170001AEST

echo "## Rename TransRate assemblies.csv file at" ; date ; echo
mv hydra12H4_qc-and-polish_TransRate_22042025170001AEST/assemblies.csv hydra12H4_qc-and-polish_TransRate_22042025170001AEST/trinity_11042025143926AEST_assemblies.csv
